### ISSUE TITLE
128x128 Level only loads at 64x64

### ISSUE THREAD

**Issue by Veggies** [lukegrahamSydney/TilesEditor#15]
I created a custom level with the size of 128x128, saved it, and opened it. The size is incorrect when opening. I'm not sure if I am doing something wrong but replicating the issue is just creating a custom level that is bigger than default, saving it, then opening it.

**Comment by Veggies** [comment]
After further investigation, this happens when saving as a .editor, .nw, or .graal. However, saving this as a .lvl correctly loads the custom size. Cannot find a way tor restore work from the .editor file though.

**Comment by lukegrahamSydney** [comment]
Yeah those formats don't support anything other than 64x64. That's for graal only. You can create a gmap though and load the gmap.

.lvl is a custom format to support anything the editor supports. LevelFormatLVL.cpp has code to show how to load it if you want to use it in your game.

**Comment by Veggies** [comment]
Okay, got it. Not really using this for any dev work just for nostalgic fun. Thanks for responding!
